using System;
using System.Collections.Generic;

#nullable disable

namespace Model.SaintEir
{
    public partial class SaintEir_InbodySRecord
    {
        public int TestID { get; set; }
        public string BelongToMember { get; set; }
        public string ServiceLoingID { get; set; }
        public string TestDatetime { get; set; }
        public string ID { get; set; }
        public string Gender { get; set; }
        public string Height { get; set; }
        public string Age { get; set; }
        public string Weight { get; set; }
        public string TestDate { get; set; }
        public string TestTime { get; set; }
        public string ICW_IntracellularWater_ { get; set; }
        public string ECW_ExtracellularWater_ { get; set; }
        public string Protein { get; set; }
        public string Minerals { get; set; }
        public string BFM_BodyFatMass_ { get; set; }
        public string TBW_TotalBodyWater_ { get; set; }
        public string FFM_FatFreeMass__LBM_LeanBodyMass_ { get; set; }
        public string SMM_SkeletalMuscleMass_ { get; set; }
        public string SLM_SoftLeanMass_ { get; set; }
        public string BMI_BodyMassIndex_ { get; set; }
        public string PBF_PercentBodyFat_ { get; set; }
        public string WHR_Waist_HipRatio_ { get; set; }
        public string BMC_BoneMineralContent_ { get; set; }
        public string BCM_BodyCellMass_ { get; set; }
        public string BMR_BasalMetabolicRate_ { get; set; }
        public string AMC_ArmMuscleCircumference_ { get; set; }
        public string VFA_VisceralFatArea_ { get; set; }
        public string DryWeight { get; set; }
        public string DryLeanMass { get; set; }
        public string MobileNumber { get; set; }
        public string VFL_VisceralFatLevel_ { get; set; }
        public string _ofProtein { get; set; }
        public string _ofMinerals { get; set; }
        public string _ofBFM { get; set; }
        public string _ofSMM { get; set; }
        public string _ofPBF_ { get; set; }
        public string _ofFFM_LBM_ { get; set; }
        public string _ofICW { get; set; }
        public string _ofECW { get; set; }
        public string _ofWeight { get; set; }
        public string _ofFFM_LBM_ofRightArm { get; set; }
        public string _ofFFM_LBM_ofLeftArm { get; set; }
        public string _ofFFM_LBM_ofTrunk { get; set; }
        public string _ofFFM_LBM_ofRightLeg { get; set; }
        public string _ofFFM_LBM_ofLeftLeg { get; set; }
        public string FFM__LBM__ofRightArm { get; set; }
        public string FFM__LBM__ofLeftArm { get; set; }
        public string FFM__LBM__ofTrunk { get; set; }
        public string FFM__LBM__ofRightLeg { get; set; }
        public string FFM__LBM__ofLeftLeg { get; set; }
        public string _ofTBWofRightArm { get; set; }
        public string _ofTBWofLeftArm { get; set; }
        public string _ofTBWofTrunk { get; set; }
        public string _ofTBWofRightLeg { get; set; }
        public string _ofTBWofLeftLeg { get; set; }
        public string _ofMuscleStrength { get; set; }
        public string _ofArmStrength { get; set; }
        public string _ofLegStrength { get; set; }
        public string _ofTBW { get; set; }
        public string _ofFFM__ofLBM { get; set; }
        public string ECF_TBFofRightArm { get; set; }
        public string ECF_TBFofLeftArm { get; set; }
        public string ECF_TBFofTrunk { get; set; }
        public string ECF_TBFofRightLeg { get; set; }
        public string ECF_TBFofLeftLeg { get; set; }
        public string ECF_TBF { get; set; }
        public string ECW_TBWofRightArm { get; set; }
        public string ECW_TBWofLeftArm { get; set; }
        public string ECW_TBWofTrunk { get; set; }
        public string ECW_TBWofRightLeg { get; set; }
        public string ECW_TBWofLeftLeg { get; set; }
        public string ECW_TBW { get; set; }
        public string FFM_LBM_ofRightArm { get; set; }
        public string FFM_LBM_ofLeftArm { get; set; }
        public string FFM_LBM_ofTrunk { get; set; }
        public string FFM_LBM_ofRightLeg { get; set; }
        public string FFM_LBM_ofLeftLeg { get; set; }
        public string BFMofRightArm { get; set; }
        public string BFMofLeftArm { get; set; }
        public string BFMofTrunk { get; set; }
        public string BFMofRightLeg { get; set; }
        public string BFMofLeftLeg { get; set; }
        public string TBWofRightArm { get; set; }
        public string TBWofLeftArm { get; set; }
        public string TBWofTrunk { get; set; }
        public string TBWofRightLeg { get; set; }
        public string TBWofLeftLeg { get; set; }
        public string PBFofRightArm { get; set; }
        public string PBFofLeftArm { get; set; }
        public string PBFofTrunk { get; set; }
        public string PBFofRightLeg { get; set; }
        public string PBFofLeftLeg { get; set; }
        public string BFM_ofRightArm { get; set; }
        public string BFM_ofLeftArm { get; set; }
        public string BFM_ofTrunk { get; set; }
        public string BFM_ofRightLeg { get; set; }
        public string BFM_ofLeftLeg { get; set; }
        public string UpperLimit_ICWNormalRange_ { get; set; }
        public string LowerLimit_ICWNormalRange_ { get; set; }
        public string UpperLimit_ECWNormalRange_ { get; set; }
        public string LowerLimit_ECWNormalRange_ { get; set; }
        public string UpperLimit_ProteinNormalRange_ { get; set; }
        public string LowerLimit_ProteinNormalRange_ { get; set; }
        public string UpperLimit_MineralsNormalRange_ { get; set; }
        public string LowerLimit_MineralsNormalRange_ { get; set; }
        public string UpperLimit_WeightNormalRange_ { get; set; }
        public string LowerLimit_WeightNormalRange_ { get; set; }
        public string UpperLimit_SMMNormalRange_ { get; set; }
        public string LowerLimit_SMMNormalRange_ { get; set; }
        public string UpperLimit_BMINormalRange_ { get; set; }
        public string LowerLimit_BMINormalRange_ { get; set; }
        public string UpperLimit_PBFNormalRange_ { get; set; }
        public string LowerLimit_PBFNormalRange_ { get; set; }
        public string UpperLimit_WHRNormalRange_ { get; set; }
        public string LowerLimit_WHRNormalRange_ { get; set; }
        public string UpperLimit_ObesityDegreeNormalRange_ { get; set; }
        public string LowerLimit_ObesityDegreeNormalRange_ { get; set; }
        public string UpperLimit_BCMNormalRange_ { get; set; }
        public string LowerLimit_BCMNormalRange_ { get; set; }
        public string UpperLimit_BMCNormalRange_ { get; set; }
        public string LowerLimit_BMCNormalRange_ { get; set; }
        public string LowerLimit_BFMNormalRange_ { get; set; }
        public string UpperLimit_BFMNormalRange_ { get; set; }
        public string LowerLimit_TBWNormalRange_ { get; set; }
        public string UpperLimit_TBWNormalRange_ { get; set; }
        public string LowerLimit_FFM_LBM_NormalRange_ { get; set; }
        public string UpperLimit_FFM_LBM_NormalRange_ { get; set; }
        public string LowerLimit_SLMNormalRange_ { get; set; }
        public string UpperLimit_SLMNormalRange_ { get; set; }
        public string ProteinEvaluation { get; set; }
        public string MineralsEvaluation { get; set; }
        public string FatEvaluation { get; set; }
        public string WeightEvaluation { get; set; }
        public string SLMEvaluation { get; set; }
        public string BFMEvaluation { get; set; }
        public string BMIEvaluation { get; set; }
        public string PBFEvaluation { get; set; }
        public string WHREvaluation { get; set; }
        public string UpperBodyBalanceEvaluation { get; set; }
        public string LowerBodyBalanceEvaluation { get; set; }
        public string Upper_LowerBodyBalanceEvaluation { get; set; }
        public string UpperBodyStrengthEvaluation { get; set; }
        public string LowerBodyStrengthEvaluation { get; set; }
        public string MuscleStrengthEvaluation { get; set; }
        public string TargetWeight { get; set; }
        public string WeightControl { get; set; }
        public string BFMControl { get; set; }
        public string FFM_LBM_Control { get; set; }
        public string InBodyScore { get; set; }
        public string MeasuredCircumferenceofNeck { get; set; }
        public string MeasuredCircumferenceofChest { get; set; }
        public string MeasuredCircumferenceofAbdomen { get; set; }
        public string MeasuredCircumferenceofHip { get; set; }
        public string MeasuredCircumferenceofRightArm { get; set; }
        public string MeasuredCircumferenceofLeftArm { get; set; }
        public string MeasuredCircumferenceofRightThigh { get; set; }
        public string MeasuredCircumferenceofLeftThigh { get; set; }
        public string MeasuredMuscleCircumferenceofRightArm { get; set; }
        public string MeasuredMuscleCircumferenceofLeftArm { get; set; }
        public string MeasuredMuscleCircumferenceofChest { get; set; }
        public string MeasuredMuscleCircumferenceofHip { get; set; }
        public string MeasuredMuscleCircumferenceofRightThigh { get; set; }
        public string MeasuredMuscleCircumferenceofLeftThigh { get; set; }
        public string MeasuredFatThicknessofRightArm { get; set; }
        public string MeasuredFatThicknessofLeftThigh { get; set; }
        public string MeasuredFatThicknessofLeftArm { get; set; }
        public string MeasuredFatThicknessofChest { get; set; }
        public string MeasuredFatThicknessofAbdomen { get; set; }
        public string MeasuredFatThicknessofRightThigh { get; set; }
        public string GrowthScore { get; set; }
        public string ObesityDegreeofaChild { get; set; }
        public string ObesityDegree { get; set; }
        public string EvaluationofFFM_LBM_ofLeftArm { get; set; }
        public string EvaluationofFFM_LBM_ofRightArm { get; set; }
        public string EvaluationofFFM_LBM_ofTrunk { get; set; }
        public string EvaluationofFFM_LBM_ofLeftLeg { get; set; }
        public string EvaluationofFFM_LBM_ofRightLeg { get; set; }
        public string EvaluationofFatofLeftArm { get; set; }
        public string EvaluationofFatofRightArm { get; set; }
        public string EvaluationofFatofTrunk { get; set; }
        public string EvaluationofFatofLeftLeg { get; set; }
        public string EvaluationofFatofRightLeg { get; set; }
        public string TBW_FFM { get; set; }
        public string Systolic { get; set; }
        public string Diastolic { get; set; }
        public string Pulse { get; set; }
        public string MeanArteryPressure { get; set; }
        public string PulsePressure { get; set; }
        public string RatePressureProduct { get; set; }
        public string _1khz_RAImpedance { get; set; }
        public string _1khz_LAImpedance { get; set; }
        public string _1khz_TRImpedance { get; set; }
        public string _1khz_RLImpedance { get; set; }
        public string _1khz_LLImpedance { get; set; }
        public string _5khz_RAImpedance { get; set; }
        public string _5khz_LAImpedance { get; set; }
        public string _5khz_TRImpedance { get; set; }
        public string _5khz_RLImpedance { get; set; }
        public string _5khz_LLImpedance { get; set; }
        public string _20khz_RAImpedance { get; set; }
        public string _20khz_LAImpedance { get; set; }
        public string _20khz_TRImpedance { get; set; }
        public string _20khz_RLImpedance { get; set; }
        public string _20khz_LLImpedance { get; set; }
        public string _50khz_RAImpedance { get; set; }
        public string _50khz_LAImpedance { get; set; }
        public string _50khz_TRImpedance { get; set; }
        public string _50khz_RLImpedance { get; set; }
        public string _50khz_LLImpedance { get; set; }
        public string _100khz_RAImpedance { get; set; }
        public string _100khz_LAImpedance { get; set; }
        public string _100khz_TRImpedance { get; set; }
        public string _100khz_RLImpedance { get; set; }
        public string _100khz_LLImpedance { get; set; }
        public string _250khz_RAImpedance { get; set; }
        public string _250khz_LAImpedance { get; set; }
        public string _250khz_TRImpedance { get; set; }
        public string _250khz_RLImpedance { get; set; }
        public string _250khz_LLImpedance { get; set; }
        public string _500khz_RAImpedance { get; set; }
        public string _500khz_LAImpedance { get; set; }
        public string _500khz_TRImpedance { get; set; }
        public string _500khz_RLImpedance { get; set; }
        public string _500khz_LLImpedance { get; set; }
        public string _1000khz_RAImpedance { get; set; }
        public string _1000khz_LAImpedance { get; set; }
        public string _1000khz_TRImpedance { get; set; }
        public string _1000khz_RLImpedance { get; set; }
        public string _1000khz_LLImpedance { get; set; }
        public string _5khz_RAReactance { get; set; }
        public string _5khz_LAReactance { get; set; }
        public string _5khz_TRReactance { get; set; }
        public string _5khz_RLReactance { get; set; }
        public string _5khz_LLReactance { get; set; }
        public string _50khz_RAReactance { get; set; }
        public string _50khz_LAReactance { get; set; }
        public string _50khz_TRReactance { get; set; }
        public string _50khz_RLReactance { get; set; }
        public string _50khz_LLReactance { get; set; }
        public string _250khz_RAReactance { get; set; }
        public string _250khz_LAReactance { get; set; }
        public string _250khz_TRReactance { get; set; }
        public string _250khz_RLReactance { get; set; }
        public string _250khz_LLReactance { get; set; }
        public string _5khz_RAPhaseAngle { get; set; }
        public string _5khz_LAPhaseAngle { get; set; }
        public string _5khz_TRPhaseAngle { get; set; }
        public string _5khz_RLPhaseAngle { get; set; }
        public string _5khz_LLPhaseAngle { get; set; }
        public string _50khz_RAPhaseAngle { get; set; }
        public string _50khz_LAPhaseAngle { get; set; }
        public string _50khz_TRPhaseAngle { get; set; }
        public string _50khz_RLPhaseAngle { get; set; }
        public string _50khz_LLPhaseAngle { get; set; }
        public string _250khz_RAPhaseAngle { get; set; }
        public string _250khz_LAPhaseAngle { get; set; }
        public string _250khz_TRPhaseAngle { get; set; }
        public string _250khz_RLPhaseAngle { get; set; }
        public string _250khz_LLPhaseAngle { get; set; }
        public string _5khz_RAResistance { get; set; }
        public string _5khz_LAResistance { get; set; }
        public string _5khz_TRResistance { get; set; }
        public string _5khz_RLResistance { get; set; }
        public string _5khz_LLResistance { get; set; }
        public string _50khz_RAResistance { get; set; }
        public string _50khz_LAResistance { get; set; }
        public string _50khz_TRResistance { get; set; }
        public string _50khz_RLResistance { get; set; }
        public string _50khz_LLResistance { get; set; }
        public string _250khz_RAResistance { get; set; }
        public string _250khz_LAResistance { get; set; }
        public string _250khz_TRResistance { get; set; }
        public string _250khz_RLResistance { get; set; }
        public string _250khz_LLResistance { get; set; }
        public string ICWofRightArm { get; set; }
        public string ICWofLeftArm { get; set; }
        public string ICWofTrunk { get; set; }
        public string ICWofRightLeg { get; set; }
        public string ICWofLeftLeg { get; set; }
        public string ECWofRightArm { get; set; }
        public string ECWofLeftArm { get; set; }
        public string ECWofTrunk { get; set; }
        public string ECWofRightLeg { get; set; }
        public string ECWofLeftLeg { get; set; }
        public string LowerLimit_ICWofArmNormalRange_ { get; set; }
        public string UpperLimit_ICWofArmNormalRange_ { get; set; }
        public string LowerLimit_ICWofTrunkNormalRange_ { get; set; }
        public string UpperLimit_ICWofTrunkNormalRange_ { get; set; }
        public string LowerLimit_ICWofLegNormalRange_ { get; set; }
        public string UpperLimit_ICWofLegNormalRange_ { get; set; }
        public string LowerLimit_ECWofArmNormalRange_ { get; set; }
        public string UpperLimit_ECWofArmNormalRange_ { get; set; }
        public string LowerLimit_ECWofTrunkNormalRange_ { get; set; }
        public string UpperLimit_ECWofTrunkNormalRange_ { get; set; }
        public string LowerLimit_ECWofLegNormalRange_ { get; set; }
        public string UpperLimit_ECWofLegNormalRange_ { get; set; }
        public string LowerLimit_FFM_LBM_ofArmNormalRange_ { get; set; }
        public string UpperLimit_FFM_LBM_ofArmNormalRange_ { get; set; }
        public string LowerLimit_FFM_LBM_ofTrunkNormalRange_ { get; set; }
        public string UpperLimit_FFM_LBM_ofTrunkNormalRange_ { get; set; }
        public string LowerLimit_FFM_LBM_ofLegNormalRange_ { get; set; }
        public string UpperLimit_FFM_LBM_ofLegNormalRange_ { get; set; }
        public string LowerLimit_TBWofArmNormalRange_ { get; set; }
        public string UpperLimit_TBWofArmNormalRange_ { get; set; }
        public string LowerLimit_TBWofTrunkNormalRange_ { get; set; }
        public string UpperLimit_TBWofTrunkNormalRange_ { get; set; }
        public string LowerLimit_TBWofLegNormalRange_ { get; set; }
        public string UpperLimit_TBWofLegNormalRange_ { get; set; }
        public string FFMI_FatFreeMassIndex_ { get; set; }
        public string FMI_FatMassIndex_ { get; set; }
        public string WholeBodyPhaseAngle50kHz { get; set; }
    }
}
